[package]
org = "ballerinax"
name = "copybook"
version = "1.0.2"
authors = ["Ballerina"]
keywords = ["copybook", "serdes", "cobol", "mainframe"]
repository = "https://github.com/ballerina-platform/module-ballerinax-copybook"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "copybook-native"
version = "1.0.2-SNAPSHOT"
path="../native/build/libs/copybook-native-1.0.2-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "copybook-commons"
version = "1.0.2"
path = "../commons/build/libs/copybook-commons-1.0.2-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "org.antlr"
artifactId = "antlr4-runtimee"
version = "4.13.1"
path="./lib/antlr4-runtime-4.13.1.jar"
